create table cliente (fecha_registro datetime(6), id bigint not null auto_increment, telefono varchar(20), email varchar(100) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
create table producto (cantidad integer not null, precio float(53) not null, fecha_actualizacion datetime(6), fecha_creacion datetime(6), id bigint not null auto_increment, codigo varchar(50) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
alter table cliente add constraint UKcmxo70m08n43599l3h0h07cc6 unique (email);
alter table producto add constraint UKkxdt4u9c4w6vveo7ylph4pd09 unique (codigo);
create table cliente (fecha_registro datetime(6), id bigint not null auto_increment, telefono varchar(20), email varchar(100) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
create table producto (cantidad integer not null, precio float(53) not null, fecha_actualizacion datetime(6), fecha_creacion datetime(6), id bigint not null auto_increment, codigo varchar(50) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
alter table cliente add constraint UKcmxo70m08n43599l3h0h07cc6 unique (email);
alter table producto add constraint UKkxdt4u9c4w6vveo7ylph4pd09 unique (codigo);
create table cliente (fecha_registro datetime(6), id bigint not null auto_increment, telefono varchar(20), email varchar(100) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
create table producto (cantidad integer not null, precio float(53) not null, fecha_actualizacion datetime(6), fecha_creacion datetime(6), id bigint not null auto_increment, codigo varchar(50) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
alter table cliente add constraint UKcmxo70m08n43599l3h0h07cc6 unique (email);
alter table producto add constraint UKkxdt4u9c4w6vveo7ylph4pd09 unique (codigo);
create table cliente (fecha_registro datetime(6), id bigint not null auto_increment, telefono varchar(20), email varchar(100) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
create table producto (cantidad integer not null, precio float(53) not null, fecha_actualizacion datetime(6), fecha_creacion datetime(6), id bigint not null auto_increment, codigo varchar(50) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
alter table cliente add constraint UKcmxo70m08n43599l3h0h07cc6 unique (email);
alter table producto add constraint UKkxdt4u9c4w6vveo7ylph4pd09 unique (codigo);
create table cliente (fecha_registro datetime(6), id bigint not null auto_increment, telefono varchar(20), email varchar(100) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
create table producto (cantidad integer not null, precio float(53) not null, fecha_actualizacion datetime(6), fecha_creacion datetime(6), id bigint not null auto_increment, codigo varchar(50) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
alter table cliente add constraint UKcmxo70m08n43599l3h0h07cc6 unique (email);
alter table producto add constraint UKkxdt4u9c4w6vveo7ylph4pd09 unique (codigo);
create table cliente (fecha_registro datetime(6), id bigint not null auto_increment, telefono varchar(20), email varchar(100) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
create table producto (cantidad integer not null, precio float(53) not null, fecha_actualizacion datetime(6), fecha_creacion datetime(6), id bigint not null auto_increment, codigo varchar(50) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
alter table cliente add constraint UKcmxo70m08n43599l3h0h07cc6 unique (email);
alter table producto add constraint UKkxdt4u9c4w6vveo7ylph4pd09 unique (codigo);
create table cliente (fecha_registro datetime(6), id bigint not null auto_increment, telefono varchar(20), email varchar(100) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
create table producto (cantidad integer not null, precio float(53) not null, fecha_actualizacion datetime(6), fecha_creacion datetime(6), id bigint not null auto_increment, codigo varchar(50) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
alter table cliente add constraint UKcmxo70m08n43599l3h0h07cc6 unique (email);
alter table producto add constraint UKkxdt4u9c4w6vveo7ylph4pd09 unique (codigo);
create table cliente (fecha_registro datetime(6), id bigint not null auto_increment, telefono varchar(20), email varchar(100) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
create table producto (cantidad integer not null, precio float(53) not null, fecha_actualizacion datetime(6), fecha_creacion datetime(6), id bigint not null auto_increment, codigo varchar(50) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
alter table cliente add constraint UKcmxo70m08n43599l3h0h07cc6 unique (email);
alter table producto add constraint UKkxdt4u9c4w6vveo7ylph4pd09 unique (codigo);
create table cliente (fecha_registro datetime(6), id bigint not null auto_increment, telefono varchar(20), email varchar(100) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
create table producto (cantidad integer not null, precio float(53) not null, fecha_actualizacion datetime(6), fecha_creacion datetime(6), id bigint not null auto_increment, codigo varchar(50) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
alter table cliente add constraint UKcmxo70m08n43599l3h0h07cc6 unique (email);
alter table producto add constraint UKkxdt4u9c4w6vveo7ylph4pd09 unique (codigo);
create table cliente (fecha_registro datetime(6), id bigint not null auto_increment, telefono varchar(20), email varchar(100) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
create table producto (cantidad integer not null, precio float(53) not null, fecha_actualizacion datetime(6), fecha_creacion datetime(6), id bigint not null auto_increment, codigo varchar(50) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
alter table cliente add constraint UKcmxo70m08n43599l3h0h07cc6 unique (email);
alter table producto add constraint UKkxdt4u9c4w6vveo7ylph4pd09 unique (codigo);
create table cliente (fecha_registro datetime(6), id bigint not null auto_increment, telefono varchar(20), email varchar(100) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
create table producto (cantidad integer not null, precio float(53) not null, fecha_actualizacion datetime(6), fecha_creacion datetime(6), id bigint not null auto_increment, codigo varchar(50) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
alter table cliente add constraint UKcmxo70m08n43599l3h0h07cc6 unique (email);
alter table producto add constraint UKkxdt4u9c4w6vveo7ylph4pd09 unique (codigo);
create table cliente (fecha_registro datetime(6), id bigint not null auto_increment, telefono varchar(20), email varchar(100) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
create table producto (cantidad integer not null, precio float(53) not null, fecha_actualizacion datetime(6), fecha_creacion datetime(6), id bigint not null auto_increment, codigo varchar(50) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
alter table cliente add constraint UKcmxo70m08n43599l3h0h07cc6 unique (email);
alter table producto add constraint UKkxdt4u9c4w6vveo7ylph4pd09 unique (codigo);
create table cliente (fecha_registro datetime(6), id bigint not null auto_increment, telefono varchar(20), email varchar(100) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
create table producto (cantidad integer not null, precio float(53) not null, fecha_actualizacion datetime(6), fecha_creacion datetime(6), id bigint not null auto_increment, codigo varchar(50) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
alter table cliente add constraint UKcmxo70m08n43599l3h0h07cc6 unique (email);
alter table producto add constraint UKkxdt4u9c4w6vveo7ylph4pd09 unique (codigo);
create table cliente (fecha_registro datetime(6), id bigint not null auto_increment, telefono varchar(20), email varchar(100) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
create table producto (cantidad integer not null, precio float(53) not null, fecha_actualizacion datetime(6), fecha_creacion datetime(6), id bigint not null auto_increment, codigo varchar(50) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
alter table cliente add constraint UKcmxo70m08n43599l3h0h07cc6 unique (email);
alter table producto add constraint UKkxdt4u9c4w6vveo7ylph4pd09 unique (codigo);
create table cliente (fecha_registro datetime(6), id bigint not null auto_increment, telefono varchar(20), email varchar(100) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
create table producto (cantidad integer not null, precio float(53) not null, fecha_actualizacion datetime(6), fecha_creacion datetime(6), id bigint not null auto_increment, codigo varchar(50) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
alter table cliente add constraint UKcmxo70m08n43599l3h0h07cc6 unique (email);
alter table producto add constraint UKkxdt4u9c4w6vveo7ylph4pd09 unique (codigo);
create table cliente (fecha_registro datetime(6), id bigint not null auto_increment, telefono varchar(20), email varchar(100) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
create table producto (cantidad integer not null, precio float(53) not null, fecha_actualizacion datetime(6), fecha_creacion datetime(6), id bigint not null auto_increment, codigo varchar(50) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
alter table cliente add constraint UKcmxo70m08n43599l3h0h07cc6 unique (email);
alter table producto add constraint UKkxdt4u9c4w6vveo7ylph4pd09 unique (codigo);
create table cliente (fecha_registro datetime(6), id bigint not null auto_increment, telefono varchar(20), email varchar(100) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
create table producto (cantidad integer not null, precio float(53) not null, fecha_actualizacion datetime(6), fecha_creacion datetime(6), id bigint not null auto_increment, codigo varchar(50) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
alter table cliente add constraint UKcmxo70m08n43599l3h0h07cc6 unique (email);
alter table producto add constraint UKkxdt4u9c4w6vveo7ylph4pd09 unique (codigo);
create table cliente (fecha_registro datetime(6), id bigint not null auto_increment, telefono varchar(20), email varchar(100) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
create table producto (cantidad integer not null, precio float(53) not null, fecha_actualizacion datetime(6), fecha_creacion datetime(6), id bigint not null auto_increment, codigo varchar(50) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
alter table cliente add constraint UKcmxo70m08n43599l3h0h07cc6 unique (email);
alter table producto add constraint UKkxdt4u9c4w6vveo7ylph4pd09 unique (codigo);
create table cliente (fecha_registro datetime(6), id bigint not null auto_increment, telefono varchar(20), email varchar(100) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
create table producto (cantidad integer not null, precio float(53) not null, fecha_actualizacion datetime(6), fecha_creacion datetime(6), id bigint not null auto_increment, codigo varchar(50) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
alter table cliente add constraint UKcmxo70m08n43599l3h0h07cc6 unique (email);
alter table producto add constraint UKkxdt4u9c4w6vveo7ylph4pd09 unique (codigo);
create table cliente (fecha_registro datetime(6), id bigint not null auto_increment, telefono varchar(20), email varchar(100) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
create table producto (cantidad integer not null, precio float(53) not null, fecha_actualizacion datetime(6), fecha_creacion datetime(6), id bigint not null auto_increment, codigo varchar(50) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
alter table cliente add constraint UKcmxo70m08n43599l3h0h07cc6 unique (email);
alter table producto add constraint UKkxdt4u9c4w6vveo7ylph4pd09 unique (codigo);
create table cliente (fecha_registro datetime(6), id bigint not null auto_increment, telefono varchar(20), email varchar(100) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
create table producto (cantidad integer not null, precio float(53) not null, fecha_actualizacion datetime(6), fecha_creacion datetime(6), id bigint not null auto_increment, codigo varchar(50) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
alter table cliente add constraint UKcmxo70m08n43599l3h0h07cc6 unique (email);
alter table producto add constraint UKkxdt4u9c4w6vveo7ylph4pd09 unique (codigo);
create table cliente (fecha_registro datetime(6), id bigint not null auto_increment, telefono varchar(20), email varchar(100) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
create table producto (cantidad integer not null, precio float(53) not null, fecha_actualizacion datetime(6), fecha_creacion datetime(6), id bigint not null auto_increment, codigo varchar(50) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
alter table cliente add constraint UKcmxo70m08n43599l3h0h07cc6 unique (email);
alter table producto add constraint UKkxdt4u9c4w6vveo7ylph4pd09 unique (codigo);
create table cliente (fecha_registro datetime(6), id bigint not null auto_increment, telefono varchar(20), email varchar(100) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
create table producto (cantidad integer not null, precio float(53) not null, fecha_actualizacion datetime(6), fecha_creacion datetime(6), id bigint not null auto_increment, codigo varchar(50) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
alter table cliente add constraint UKcmxo70m08n43599l3h0h07cc6 unique (email);
alter table producto add constraint UKkxdt4u9c4w6vveo7ylph4pd09 unique (codigo);
create table cliente (fecha_registro datetime(6), id bigint not null auto_increment, telefono varchar(20), email varchar(100) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
create table producto (cantidad integer not null, precio float(53) not null, fecha_actualizacion datetime(6), fecha_creacion datetime(6), id bigint not null auto_increment, codigo varchar(50) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
alter table cliente add constraint UKcmxo70m08n43599l3h0h07cc6 unique (email);
alter table producto add constraint UKkxdt4u9c4w6vveo7ylph4pd09 unique (codigo);
create table cliente (fecha_registro datetime(6), id bigint not null auto_increment, telefono varchar(20), email varchar(100) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
create table producto (cantidad integer not null, precio float(53) not null, fecha_actualizacion datetime(6), fecha_creacion datetime(6), id bigint not null auto_increment, codigo varchar(50) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
alter table cliente add constraint UKcmxo70m08n43599l3h0h07cc6 unique (email);
alter table producto add constraint UKkxdt4u9c4w6vveo7ylph4pd09 unique (codigo);
create table cliente (fecha_registro datetime(6), id bigint not null auto_increment, telefono varchar(20), email varchar(100) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
create table producto (cantidad integer not null, precio float(53) not null, fecha_actualizacion datetime(6), fecha_creacion datetime(6), id bigint not null auto_increment, codigo varchar(50) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
alter table cliente add constraint UKcmxo70m08n43599l3h0h07cc6 unique (email);
alter table producto add constraint UKkxdt4u9c4w6vveo7ylph4pd09 unique (codigo);
create table cliente (fecha_registro datetime(6), id bigint not null auto_increment, telefono varchar(20), email varchar(100) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
create table producto (cantidad integer not null, precio float(53) not null, fecha_actualizacion datetime(6), fecha_creacion datetime(6), id bigint not null auto_increment, codigo varchar(50) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
alter table cliente add constraint UKcmxo70m08n43599l3h0h07cc6 unique (email);
alter table producto add constraint UKkxdt4u9c4w6vveo7ylph4pd09 unique (codigo);
create table cliente (fecha_registro datetime(6), id bigint not null auto_increment, telefono varchar(20), email varchar(100) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
create table producto (cantidad integer not null, precio float(53) not null, fecha_actualizacion datetime(6), fecha_creacion datetime(6), id bigint not null auto_increment, codigo varchar(50) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
alter table cliente add constraint UKcmxo70m08n43599l3h0h07cc6 unique (email);
alter table producto add constraint UKkxdt4u9c4w6vveo7ylph4pd09 unique (codigo);
create table cliente (fecha_registro datetime(6), id bigint not null auto_increment, telefono varchar(20), email varchar(100) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
create table producto (cantidad integer not null, precio float(53) not null, fecha_actualizacion datetime(6), fecha_creacion datetime(6), id bigint not null auto_increment, codigo varchar(50) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
alter table cliente add constraint UKcmxo70m08n43599l3h0h07cc6 unique (email);
alter table producto add constraint UKkxdt4u9c4w6vveo7ylph4pd09 unique (codigo);
create table cliente (fecha_registro datetime(6), id bigint not null auto_increment, telefono varchar(20), email varchar(100) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
create table producto (cantidad integer not null, precio float(53) not null, fecha_actualizacion datetime(6), fecha_creacion datetime(6), id bigint not null auto_increment, codigo varchar(50) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
alter table cliente add constraint UKcmxo70m08n43599l3h0h07cc6 unique (email);
alter table producto add constraint UKkxdt4u9c4w6vveo7ylph4pd09 unique (codigo);
create table cliente (fecha_registro datetime(6), id bigint not null auto_increment, telefono varchar(20), email varchar(100) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
create table producto (cantidad integer not null, precio float(53) not null, fecha_actualizacion datetime(6), fecha_creacion datetime(6), id bigint not null auto_increment, codigo varchar(50) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
alter table cliente add constraint UKcmxo70m08n43599l3h0h07cc6 unique (email);
alter table producto add constraint UKkxdt4u9c4w6vveo7ylph4pd09 unique (codigo);
create table cliente (fecha_registro datetime(6), id bigint not null auto_increment, telefono varchar(20), email varchar(100) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
create table producto (cantidad integer not null, precio float(53) not null, fecha_actualizacion datetime(6), fecha_creacion datetime(6), id bigint not null auto_increment, codigo varchar(50) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
alter table cliente add constraint UKcmxo70m08n43599l3h0h07cc6 unique (email);
alter table producto add constraint UKkxdt4u9c4w6vveo7ylph4pd09 unique (codigo);
create table cliente (fecha_registro datetime(6), id bigint not null auto_increment, telefono varchar(20), email varchar(100) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
create table producto (cantidad integer not null, precio float(53) not null, fecha_actualizacion datetime(6), fecha_creacion datetime(6), id bigint not null auto_increment, codigo varchar(50) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
alter table cliente add constraint UKcmxo70m08n43599l3h0h07cc6 unique (email);
alter table producto add constraint UKkxdt4u9c4w6vveo7ylph4pd09 unique (codigo);
create table cliente (fecha_registro datetime(6), id bigint not null auto_increment, telefono varchar(20), email varchar(100) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
create table producto (cantidad integer not null, precio float(53) not null, fecha_actualizacion datetime(6), fecha_creacion datetime(6), id bigint not null auto_increment, codigo varchar(50) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
alter table cliente add constraint UKcmxo70m08n43599l3h0h07cc6 unique (email);
alter table producto add constraint UKkxdt4u9c4w6vveo7ylph4pd09 unique (codigo);
create table cliente (fecha_registro datetime(6), id bigint not null auto_increment, telefono varchar(20), email varchar(100) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
create table producto (cantidad integer not null, precio float(53) not null, fecha_actualizacion datetime(6), fecha_creacion datetime(6), id bigint not null auto_increment, codigo varchar(50) not null, nombre varchar(255) not null, primary key (id)) engine=InnoDB;
alter table cliente add constraint UKcmxo70m08n43599l3h0h07cc6 unique (email);
alter table producto add constraint UKkxdt4u9c4w6vveo7ylph4pd09 unique (codigo);
